### ISSUE TITLE
[Bug] migrations/SQLite: file does not exist

### ISSUE THREAD

**Issue by lightmaster** [aleksasiriski/autoscan#1]
I switched to your fork of autoscan and added the config for my Postgresql server. When I try to start the autoscan container, I get this error over and over again in the log:

`Feb 26 00:55:07 **FTL** Failed initialising processor error="migrate: parse: read migrations: open migrations/sqlite: file does not exist"`

**Comment by aleksasiriski** [comment]
It should be fixed now, let me know how it goes after you pull the latest image or tag v1.3.0

**Comment by lightmaster** [comment]
Now I'm getting this:

`Feb 26 10:41:53 FTL Failed initialising processor error="migrate: migrate: 1_init.sql: exec: pq: syntax error at or near \"PRIMARY\""`

**Comment by aleksasiriski** [comment]
I don't know how that got past me, it's fixed now.

**Comment by lightmaster** [comment]
No errors now. There's nothing in the log about PostgreSQL, but I do see a `scan` table that's been created in the `autoscan` database.

**Comment by aleksasiriski** [comment]
I haven't implemented any info logging, since Sqlite didn't have any either.. I could add a simple Info when the first connection is made. But as you saw the errors are present and believe it or not are very useful for debugging

**Comment by aleksasiriski** [comment]
You could also enable DEBUG with -v or TRACE with -vv arguments and it'll become much more verbose about what is happening, but I tested this and it works without issues.
