### ISSUE TITLE
Plex v1.32.7 broke autoscan, fix already implemented by upstream Cloudbox

### ISSUE THREAD

**Issue by lightmaster** [aleksasiriski/autoscan#10]
The Cloudbox upstream has added a fix for Plex v1.32.7, which broke autoscan. PUT/POST methods no long work and throw a 404 error, so they switched to using GET instead.

https://github.com/Cloudbox/autoscan/commit/e5575d5ffd35141615e9e144ff42d99aaa5b8af7

https://github.com/Cloudbox/autoscan/issues/218

**Comment by lightmaster** [comment]
I see that there was already a commit to fix this in this repo, but docker is still pulling a version that doesn't have this fix. Using the following URL in my docker-compose `ghcr.io/aleksasiriski/autoscan:latest`

**Comment by aleksasiriski** [comment]
Should be fixed in v1.6.1

**Comment by lightmaster** [comment]
Its working now. Apparently using the tag `main` or `lastest` was preventing it from updating past v1.4.1. Set it to just use `ghcr.io/aleksasiriski/autoscan` and it pulled 1.6.1
