### ISSUE TITLE
Add option to refresh Plex metadata?

### ISSUE THREAD

**Issue by Kreeblah** [aleksasiriski/autoscan#11]
It would be neat if there could be an option added to call the Plex [metadata refresh endpoint](https://www.plexopedia.com/plex-media-server/api/library/refresh-metadata/) in addition to or instead of a library rescan.  This would be my primary use case for this, since I've got Bazarr downloading subtitles for me, but Plex doesn't pick up on them unless the metadata is refreshed for a movie/episode/whatever.  It ignores new external subtitle files on just a rescan.

**Comment by aleksasiriski** [comment]
I don't use Plex so this is low priority for me, but PRs are welcome. I'd be more interested in adding support to refresh Bazarr subtitles to Jellyfin (and after that if it isn't much work I could add support for Plex, but will need someone else to test if it works)

**Comment by Kreeblah** [comment]
It ended up being a simpler thing to do than I expected, so https://github.com/aleksasiriski/autoscan/pull/13 is available.

I'd also be interested in something equivalent for Jellyfin, so I might take a look at that as well at some point, though at first glance, it'd be a bigger lift.  It looks like the API to refresh metadata in Jellyfin is more fine-grained, which is good, though it also means that there's more work to do in narrowing down the item to refresh.

**Comment by alneven** [comment]
humm, I'm using `bazarr` and it has a `post-processing` script option if the subtitle was added

I just trigger autoscan for manual scan and all the .SRT files got picked up by Plex after that
```
curl -sG -X POST --data-urlencode dir={{directory}} http://AUTOSCAN_IP:3030/triggers/manual
```

and if you add SRT manual outside of bazarr or any tool, like upload it beside the media file
you could just add a bash script which triggers this curl script from crontab
