### ISSUE TITLE
[Bug] - "migrate: parse: read migration: open migrations\\postgres\\1_init.sql: file does not exist"

### ISSUE THREAD

**Issue by Yankees4life** [aleksasiriski/autoscan#2]
Hello there

Thanks for keeping this tool going. I tried to run it for the first time on windows and I'm getting this weird error

>Apr 27 04:46:48 FTL Failed initialising processor error="migrate: parse: read migration: open migrations\\postgres\\1_init.sql: file does not exist"

Any ideas? I'm using the latest release btw (v.1.4.1)

**Comment by aleksasiriski** [comment]
I'll look into it, probably Windows path using backslashes.. I haven't tested it on Windows since I don't use it.

**Comment by aleksasiriski** [comment]
> open migrations\postgres

Hi, sorry for not getting back sooner. I can see that you're using Postgresql, would you mind testing with SQLite and see if you get the same error? Of course, first download the latest version just in case.

**Comment by Yankees4life** [comment]
> > open migrations\postgres
> 
> Hi, sorry for not getting back sooner. I can see that you're using Postgresql, would you mind testing with SQLite and see if you get the same error? Of course, first download the latest version just in case.

Got this error now.
`May 13 01:05:33 FTL Failed initialising processor error="migrate: parse: read migration: open migrations\\sqlite\\1_init.sql: file does not exist"`

Don't think its progres thats causing the issue. Using latest prerelease BTW

**Comment by aleksasiriski** [comment]
I probably have to move that sql directly inside the code so that it works on Windows, will ping you here when it's done.

**Comment by aleksasiriski** [comment]
https://github.com/golang/go/issues/44305

**Comment by aleksasiriski** [comment]
Hmm actually the path it set correctly `migrations\\sqlite\\1_init.sql`. I'll setup a VM to test what's actually wrong

**Comment by Yankees4life** [comment]
Any updates on this? Cheers

**Comment by aleksasiriski** [comment]
Haven't got around to it because of my studies, and priorities lying elsewhere.. Are you doing any path rewrites in your config?

**Comment by aleksasiriski** [comment]
I've setup a VM, and it's as you describe (regardless of config), probably Go embed not embedding the migrations correctly for windows

**Comment by aleksasiriski** [comment]
So sorry this took so long, and it was literally [this](https://github.com/aleksasiriski/autoscan/issues/2#issuecomment-1546703105) but I had been looking [here](https://github.com/aleksasiriski/autoscan/blob/fe954b4325d72ecc1205d3af79d76cdf5460414d/migrate/util.go#L85) instead of down [here](https://github.com/aleksasiriski/autoscan/blob/fe954b4325d72ecc1205d3af79d76cdf5460414d/migrate/util.go#L104)... I thought the error had an `s` at the end, but it didn't.

I've successfully started autoscan on Win10 VM via powershell now, no errors (:
