### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by imjuzcy** [aleksasiriski/autoscan#8]
1. The indentation for `database:` configuration [here](https://github.com/aleksasiriski/autoscan/blob/23b2fdd533ec56a8e13cef8d22d625dc94a21968/README.md?plain=1#L299) (Line 299 to 305) is two spaces too deep.

2. Typo [here](https://github.com/aleksasiriski/autoscan/blob/23b2fdd533ec56a8e13cef8d22d625dc94a21968/README.md?plain=1#L600). `ghcr.io` instead of `ghrc.io`

**Comment by aleksasiriski** [comment]
Thanks, fixed.
